###############################################################################
# © Copyright IBM Corporation 2020, 2021
###############################################################################
# This sample playbook demonstrates basic data set operations using modules
# included in the Red Hat Ansible Certified  Content for IBM Z core collection.
#
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventories data_set_basics.yml
#  ansible-playbook -i inventories data_set_basics.yml -v
#
#  Additional facts for this playbook can be configured to override the defaults
#  by reviewing the "Fact setting" section of this playbook, for example,
#  `data_set_name` and `system_name`.
#
# Requirements:
#   IBM z/OS core collection 1.2.0 or later
#
# Configure:
#   tgt_tmp_dir - this is the USS directory on the target which will be written
#                 to for this example.
#
# Optional:
#   data_set_name - this is the data set name that will be created during
#                   execution of this sample.
#   pds_name - this is the pds name that will be used during execution of this
#              sample.
#   system_name - this is the system name that will be used during this example,
#                 determined by executing `uname -n` on the target.
###############################################################################
---
- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  vars:
    src: "{{ src | default('/tmp/default.txt') }}"
    dest: "{{ dest | default('ANSIBLE.DATASET(MEMBER)') }}"
    remote_src: "{{ remote_src | default(true) }}"
  environment: "{{ environment_vars }}"

  tasks:
    - name: Copy content to z/OS dataset
      zos_copy:
        src: "{{ src }}"
        dest: "{{ dest }}"
        remote_src: "{{ remote_src }}"
      register: result

    - name: Display copy result
      debug:
        msg: "{{ result }}"
