---
- name: Aggiornamento Dataset z/OS
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:
    - name: Modifica riga
      ibm.ibm_zos_core.zos_lineinfile:
        src: "{{ dataset_dest | upper }}" 
        regexp: "{{ regex_target }}"
        line: "{{ new_content }}"
        state: present
      register: line_result

    - name: Debug in caso di errore
      ansible.builtin.debug:
        var: line_result
      when: line_result.failed
