//MQREAD   JOB (ACCT),'READ MSG',CLASS=A,MSGCLASS=X
//STEP1    EXEC PGM=CSQUTIL,PARM='CSQ9'
//STEPLIB  DD DISP=SHR,DSN=MQM.V9R3M0.SCSQAUTH
//         DD DISP=SHR,DSN=MQM.V9R3M0.SCSQANLE
//SYSPRINT DD SYSOUT=*
//SYSIN    DD *
 SCOMMAND
 DISPLAY QUEUE('DEMO.SORGENTE.QUEUE') ALL
 COPY QUEUE('DEMO.SORGENTE.QUEUE') DDNAME(SYSPRINT)
/*
