- name: Start MQ Queue Manager in Wazi
  hosts: zos_managed_nodes
  collections:
    - ibm.ibm_zos_core
  tasks:
    - name: Issue START QMGR operator command
      zos_operator:
        cmd: "+CSQ1 START QMGR"
      register: qmgr_start_output

    - name: Display Output
      debug:
        var: qmgr_start_output.content
